language: node_js
node_js:
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - ./nodeserver.sh > /dev/null &

script:
  - npm test

sudo: false

git:
  depth: 10
